update all tests

diff --git a/.github/workflows/unit-test.yml b/.github/workflows/unit-test.yml
--- a/.github/workflows/unit-test.yml
+++ b/.github/workflows/unit-test.yml
@@ -103,7 +103,7 @@ jobs:
 
       - name: Test if the REST API works
         run: |
-            sleep 100
+            sleep 10
             docker logs palworld-server
             if ! docker exec palworld-server rest-cli info | grep -q "\"version\"\:"; then
               echo "Server may not have started successfully."
@@ -131,7 +131,6 @@ jobs:
             nc -z -u -v 127.0.0.1 8211 || exit 7
             nc -z -u -v 127.0.0.1 27015 || exit 8
             nc -z -v 127.0.0.1 25575 || exit 9
-            nc -z -v 127.0.0.1 8212 || exit 10
 
       - name: Test the backup script
         run: |
@@ -252,16 +251,27 @@ jobs:
       #       fi
       - name: Test if the REST API works
         run: |
-            sleep 100
-
+            sleep 10
+            docker logs palworld-server
             if ! docker exec palworld-server rest-cli info | grep -q "\"version\"\:"; then
               echo "Server may not have started successfully."
               exit 4
             fi
-            OUTPUT=$(docker exec palworld-server rest-cli announce "Hello, Palworld!" 2>&1)
-            if [[ $OUTPUT != *{"message":"Hello, Palworld!"}* ]]; then
-              echo "Error: Unexpected output - $OUTPUT"
-              exit 5
+            docker exec palworld-server rest-cli announce "Hello, Palworld!"
+            if docker logs palworld-server 2>&1 | grep -q "REST accessed endpoint /v1/api/announce OK"; then
+                echo "Announce OK — continuing."
+                exit 0
+            else
+                echo "Required log entry not found — exiting with code 5."
+                exit 5
+            fi
+            docker exec palworld-server rest-cli save
+            if docker logs palworld-server 2>&1 | grep -q "REST accessed endpoint /v1/api/save OK"; then
+                echo "Save OK — continuing."
+                exit 0
+            else
+                echo "Required log entry not found — exiting with code 5."
+                exit 5
             fi
 
       - name: Test if port 8211, 27015, 25575 and 8212 are listening
@@ -269,7 +279,6 @@ jobs:
             nc -z -u -v 127.0.0.1 8211 || exit 7
             nc -z -u -v 127.0.0.1 27015 || exit 8
             nc -z -v 127.0.0.1 25575 || exit 9
-            nc -z -v 127.0.0.1 8212 || exit 10
 
       - name: Test the backup script
         run: |
@@ -395,16 +404,27 @@ jobs:
       #       fi
       - name: Test if the REST API works
         run: |
-            sleep 100
-
+            sleep 10
+            docker logs palworld-server
             if ! docker exec palworld-server-${{ github.run_id }} rest-cli info | grep -q "\"version\"\:"; then
               echo "Server may not have started successfully."
               exit 4
             fi
-            OUTPUT=$(docker exec palworld-server-${{ github.run_id }} rest-cli announce "Hello, Palworld!" 2>&1)
-            if [[ $OUTPUT != *{"message":"Hello, Palworld!"}* ]]; then
-              echo "Error: Unexpected output - $OUTPUT"
-              exit 5
+            docker exec palworld-server-${{ github.run_id }} rest-cli announce "Hello, Palworld!"
+            if docker logs palworld-server-${{ github.run_id }} 2>&1 | grep -q "REST accessed endpoint /v1/api/announce OK"; then
+                echo "Announce OK — continuing."
+                exit 0
+            else
+                echo "Required log entry not found — exiting with code 5."
+                exit 5
+            fi
+            docker exec palworld-server-${{ github.run_id }} rest-cli save
+            if docker logs palworld-server-${{ github.run_id }} 2>&1 | grep -q "REST accessed endpoint /v1/api/save OK"; then
+                echo "Save OK — continuing."
+                exit 0
+            else
+                echo "Required log entry not found — exiting with code 5."
+                exit 5
             fi
 
       - name: Test if port 8211, 27015, 25575 and 8212 are listening
@@ -412,7 +432,6 @@ jobs:
             nc -z -u -v 127.0.0.1 8211 || exit 7
             nc -z -u -v 127.0.0.1 27015 || exit 8
             nc -z -v 127.0.0.1 25575 || exit 9
-            nc -z -v 127.0.0.1 8212 || exit 10
 
       - name: Test the backup script
         run: |
