update rest tests

diff --git a/.github/workflows/unit-test.yml b/.github/workflows/unit-test.yml
--- a/.github/workflows/unit-test.yml
+++ b/.github/workflows/unit-test.yml
@@ -109,10 +109,21 @@ jobs:
               echo "Server may not have started successfully."
               exit 4
             fi
-            OUTPUT=$(docker exec palworld-server rest-cli announce "Hello, Palworld!" 2>&1)
-            if [[ $OUTPUT != *{"message":"Hello, Palworld!"}* ]]; then
-              echo "Error: Unexpected output - $OUTPUT"
-              exit 5
+            docker exec palworld-server rest-cli announce "Hello, Palworld!"
+            if docker logs palworld-server 2>&1 | grep -q "REST accessed endpoint /v1/api/announce OK"; then
+                echo "Announce OK — continuing."
+                exit 0
+            else
+                echo "Required log entry not found — exiting with code 5."
+                exit 5
+            fi
+            docker exec palworld-server rest-cli save
+            if docker logs palworld-server 2>&1 | grep -q "REST accessed endpoint /v1/api/save OK"; then
+                echo "Save OK — continuing."
+                exit 0
+            else
+                echo "Required log entry not found — exiting with code 5."
+                exit 5
             fi
 
       - name: Test if port 8211, 27015, 25575 and 8212 are listening
