test if rcon.yaml is valid and if rcon works

diff --git a/.github/workflows/unit-test.yml b/.github/workflows/unit-test.yml
--- a/.github/workflows/unit-test.yml
+++ b/.github/workflows/unit-test.yml
@@ -3,6 +3,8 @@ name: Unit-test
 on:  # yamllint disable-line rule:truthy
   pull_request:
   workflow_call:
+  push:
+    branches: [unittest]
 
 concurrency:
   group: '${{ github.workflow }} @ ${{ github.ref }}'
@@ -22,6 +24,7 @@ jobs:
       - name: Build and export to Docker
         uses: docker/build-push-action@v5
         with:
+          file: ./Dockerfile
           load: true
           tags: ${{ github.run_id }}
           platforms: linux/amd64
@@ -50,19 +53,47 @@ jobs:
 
               if [ $ELAPSED_TIME -gt $TIMEOUT_SECONDS ]; then
                 echo "Timeout reached. Server failed to start within $TIMEOUT_SECONDS seconds."
+                printf "\e[0;32m%s\e[0m\n" "*****Container LOGS*****"
+                docker logs palworld-server
                 exit 1  # or handle the failure accordingly
               fi
-
-              echo "Waiting for server to start..."
-              sleep 5
             done
 
-      - name: Test if server is up and running
+      - name: Test if rcon.yaml is valid
+        run: |
+            RCON_PORT=$(grep "^RCON_PORT=" .env.example | cut -d '=' -f2)
+            ADMIN_PASSWORD=$(grep "^ADMIN_PASSWORD=" .env.example | cut -d '=' -f2)
+
+            ADDRESS=$(docker exec palworld-server cat /home/steam/server/rcon.yaml | grep "^  address:" | awk '{print $2}' | tr -d '"')
+            PASSWORD=$(docker exec palworld-server cat /home/steam/server/rcon.yaml | grep "^  password:" | awk '{print $2}' | tr -d '"')
+
+            if [ "$RCON_PORT" != "$ADDRESS" ]; then
+              echo "Error: $RCON_PORT in .env.example != $ADDRESS in rcon.yaml."
+              exit 1
+            fi
+
+            if [ "$ADMIN_PASSWORD" != "$PASSWORD" ]; then
+              echo "Error: $ADMIN_PASSWORD in .env.example != $PASSWORD in rcon.yaml."
+              exit 1
+            fi
+
+      - name: Test if rcon works
         run: |
             sleep 5
             if ! docker exec palworld-server rcon-cli Info | grep -q "Welcome to Pal Server"; then
               echo "Server may not have started successfully."
               exit 1
+            fi
+
+            OUTPUT=$(docker exec -it palworld-server rcon-cli "Broadcast test" 2>&1)
+            if [[ $OUTPUT != *"Broadcasted: test"* ]]; then
+              echo "Error: Unexpected output - $OUTPUT"
+              exit 1
+            fi
+
+            OUTPUT=$(docker exec -it palworld-server rcon-cli save 2>&1)
+            if [[ $OUTPUT != *"Complete Save"* ]]; then
+              echo "Error: Unexpected output - $OUTPUT"
             fi
 
       - name: Test if port 8211, 27015 and 25575 are listening
@@ -73,23 +104,28 @@ jobs:
 
       - name: Test the backup script
         run: |
-          docker exec palworld-server backup
-          if [ ! -f ./palworld/backups/palworld-save-*.tar.gz ]; then
-            echo "Backup file not found. Backup command may have failed."
-            exit 1
-          fi
+            docker exec palworld-server backup
+            if [ ! -f ./palworld/backups/palworld-save-*.tar.gz ]; then
+              echo "Backup file not found. Backup command may have failed."
+              exit 1
+            fi
 
       - name: Test if PalWorldSettings.ini is valid
         run: |
-          if ! grep -q "\[\/Script\/Pal.PalGameWorldSettings\]" ./palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini; then
-            echo "Error: PalWorldSettings.ini is missing the required section [/Script/Pal.PalGameWorldSettings]."
-            exit 1
-          fi
+            if [ ! -f ./palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini ]; then
+              echo "Error: PalWorldSettings.ini file is missing."
+              exit 1
+            fi
 
-          if ! grep -q "^OptionSettings=\(.*\)" ./palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini; then
-            echo "Error: PalWorldSettings.ini is missing or has an invalid OptionSettings section."
-            exit 1
-          fi
+            if ! grep -q "\[\/Script\/Pal.PalGameWorldSettings\]" ./palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini; then
+              echo "Error: PalWorldSettings.ini is missing the required section [/Script/Pal.PalGameWorldSettings]."
+              exit 1
+            fi
+
+            if ! grep -q "^OptionSettings=\(.*\)" ./palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini; then
+              echo "Error: PalWorldSettings.ini is missing or has an invalid OptionSettings section."
+              exit 1
+            fi
 
   unit-test-arm64:
     name: Docker - Test (arm64)
@@ -137,19 +173,50 @@ jobs:
 
               if [ $ELAPSED_TIME -gt $TIMEOUT_SECONDS ]; then
                 echo "Timeout reached. Server failed to start within $TIMEOUT_SECONDS seconds."
+                printf "\e[0;32m%s\e[0m\n" "*****Container LOGS*****"
+                docker logs palworld-server
                 exit 1  # or handle the failure accordingly
               fi
-
-              echo "Waiting for server to start..."
-              sleep 5
             done
 
-      - name: Test if server is up and running
+            printf "\e[0;32m%s\e[0m\n" "*****Container LOGS*****"
+            docker logs palworld-server
+
+      - name: Test if rcon.yaml is valid
+        run: |
+            RCON_PORT=$(grep "^RCON_PORT=" .env.example | cut -d '=' -f2)
+            ADMIN_PASSWORD=$(grep "^ADMIN_PASSWORD=" .env.example | cut -d '=' -f2)
+
+            ADDRESS=$(docker exec palworld-server cat /home/steam/server/rcon.yaml | grep "^  address:" | awk '{print $2}' | tr -d '"')
+            PASSWORD=$(docker exec palworld-server cat /home/steam/server/rcon.yaml | grep "^  password:" | awk '{print $2}' | tr -d '"')
+
+            if [ "$RCON_PORT" != "$ADDRESS" ]; then
+              echo "Error: $RCON_PORT in .env.example != $ADDRESS in rcon.yaml."
+              exit 1
+            fi
+
+            if [ "$ADMIN_PASSWORD" != "$PASSWORD" ]; then
+              echo "Error: $ADMIN_PASSWORD in .env.example != $PASSWORD in rcon.yaml."
+              exit 1
+            fi
+
+      - name: Test if rcon works
         run: |
             sleep 100
             if ! docker exec palworld-server rcon-cli Info | grep -q "Welcome to Pal Server"; then
               echo "Server may not have started successfully."
               exit 1
+            fi
+
+            OUTPUT=$(docker exec -it palworld-server rcon-cli "Broadcast test" 2>&1)
+            if [[ $OUTPUT != *"Broadcasted: test"* ]]; then
+              echo "Error: Unexpected output - $OUTPUT"
+              exit 1
+            fi
+
+            OUTPUT=$(docker exec -it palworld-server rcon-cli save 2>&1)
+            if [[ $OUTPUT != *"Complete Save"* ]]; then
+              echo "Error: Unexpected output - $OUTPUT"
             fi
 
       - name: Test if port 8211, 27015 and 25575 are listening
@@ -160,20 +227,25 @@ jobs:
 
       - name: Test the backup script
         run: |
-          docker exec palworld-server backup
-          if [ ! -f ./palworld/backups/palworld-save-*.tar.gz ]; then
-            echo "Backup file not found. Backup command may have failed."
-            exit 1
-          fi
+            docker exec palworld-server backup
+            if [ ! -f ./palworld/backups/palworld-save-*.tar.gz ]; then
+              echo "Backup file not found. Backup command may have failed."
+              exit 1
+            fi
 
       - name: Test if PalWorldSettings.ini is valid
         run: |
-          if ! grep -q "\[\/Script\/Pal.PalGameWorldSettings\]" ./palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini; then
-            echo "Error: PalWorldSettings.ini is missing the required section [/Script/Pal.PalGameWorldSettings]."
-            exit 1
-          fi
+            if [ ! -f ./palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini ]; then
+              echo "Error: PalWorldSettings.ini file is missing."
+              exit 1
+            fi
 
-          if ! grep -q "^OptionSettings=\(.*\)" ./palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini; then
-            echo "Error: PalWorldSettings.ini is missing or has an invalid OptionSettings section."
-            exit 1
-          fi
+            if ! grep -q "\[\/Script\/Pal.PalGameWorldSettings\]" ./palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini; then
+              echo "Error: PalWorldSettings.ini is missing the required section [/Script/Pal.PalGameWorldSettings]."
+              exit 1
+            fi
+
+            if ! grep -q "^OptionSettings=\(.*\)" ./palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini; then
+              echo "Error: PalWorldSettings.ini is missing or has an invalid OptionSettings section."
+              exit 1
+            fi
